#!/bin/bash

[ -z "$1" ] && echo 'Usage: ./gen [session or lib]' && exit 1

if [ "$1" == "std" ] || [ "$1" == "exam" ] || [ "$1" == "lib" ]
then
    for line in $(cat packagelist )
    do
	echo $line | sed -e "s/,\([^,]\)/ \1/g;s/,/ ,/g" > .tmp_exec &&
	    read pack lib std exam trash < .tmp_exec
	case $1 in
	    std)
		[ "$lib" != "lib" ] && [ "$std" == "TRUE" ] && echo $pack ;;
	    exam)
		[ "$lib" != "lib" ] && [ "$exam" == "TRUE" ] && echo $pack ;;
	    *)
		[ "$lib" == "lib" ] && echo $pack ;;
	esac
    done
    unset pack lib std exam trash
    rm .tmp_exec
else
    echo 'Usage: ./gen [session or lib]'
fi
